name: geo_flix
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: 5.3.3
  flutter_spinkit: ^5.2.0
  custom_radio_grouped_button: ^2.2.1
  #flutter_datetime_picker: ^1.5.1
  table_calendar: ^3.0.7
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.0.13
  conditional_builder_null_safety: ^0.0.6
  cached_network_image: ^3.2.0
  smooth_page_indicator: ^1.0.0+2
  motion_toast: ^2.1.1
  carousel_slider: ^4.0.0
  bubble_bottom_bar: ^2.0.0
  chart_sparkline: 1.0.14
  parent_child_checkbox: ^0.0.5
  flutter_screenutil: ^5.9.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  android_id: 0.3.6
  flutter_local_notifications: 16.1.0
  easy_geofencing: ^0.2.0
  msh_checkbox: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/gif/
    - assets/logo/
    - assets/back.jpg

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf

    - family: Sansation-Bold
      fonts:
        - asset: assets/fonts/Sansation-Bold.ttf

    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter-Regular.ttf


